CREATE TABLE "Dish" 
( 
 "Id"  int Generated by default as identity NOT NULL primary key , 
 "Name" varchar(30) NOT NULL , 
 "Cost" real NOT NULL,
 "Category" varchar(50) not null,
 "Description" varchar(500),
 "ImageUrl" varchar(500)
); 
 
CREATE TABLE "User" 
( 
 "Id"  int Generated by default as identity NOT NULL primary key , 
 "Login"    varchar(15) NOT NULL , 
 "Password" varchar(15) NOT NULL , 
 "FullName" varchar(50) NOT NULL , 
 "RoleId"     int NOT NULL constraint fk_RoleId foreign key("RoleId") references "Role"("Id") on delete cascade  
); 

select * from "User"
 
CREATE TABLE "Order" 
( 
 "Id"  int Generated by default as identity NOT NULL primary key , 
 "Status"     int NOT NULL , 
 "SubmittedAt"     timestamp NOT NULL , 
 "Address"    varchar(50) NOT NULL , 
 "CustomerId" int NOT NULL , 
 "EmployeeId"  int NULL																																																			, 
 constraint fk_EmployeeId foreign key("EmployeeId") references "User"("Id"), 
 constraint fk_CustomerId foreign key("CustomerId") references "User"("Id") on delete cascade
); 
 
CREATE TABLE "OrderedDish" 
( 
 "Id"  int Generated by default as identity NOT NULL primary key , 
 "OrderId" int NOT NULL , 
 "DishId"  int NOT NULL , 
 constraint fk_OrderId
   foreign key("OrderId")
   references "Order"("Id")
   on delete cascade;, 
 constraint  fk_DishId
   foreign key("DishId")
   references "Dish"("Id")
   on delete cascade;
);

create table "Role"
(
 	"Id"  int Generated by default as identity NOT NULL primary key,
	"RoleName" varchar(50) not null
);